apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-static-deployment
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: us-static-site
  template:
    metadata:
      labels:
        app: us-static-site
    spec:
      containers:
        - name: us-static-container
          image: utkarshashelar/us-static-site:v2 
          ports:
            - containerPort: 80